---
title: "Final_Model"
author: "Tyler Cobian, Jeremy Knox, Alex Smith"
date: "5/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the packages
```{r}
library(tidyverse)
library(sensitivity)
library(deSolve)
library(ggplot2)
```

```{r SEIR Model}
SEIR <- function(time, state, parms) {
  # SEIR model with social distancing of rho
  # Model adapted from https://cran.r-project.org/web/packages/shinySIR/vignettes/Vignette.html and
  # https://towardsdatascience.com/social-distancing-to-slow-the-coronavirus-768292f04296
  # PARMS:
  # α is the inverse of the incubation period (1/t_incubation)
  # β is the average contact rate in the population
  # γ is the inverse of the mean infectious period (1/t_infectious)
  # ρ rho is the social distancing effect, 0 being everyone locked down
  # VARIABLES:
  # S = SUSCEPTIBLE, E = EXPOSED, I = INFECTED, R = RECOVERED
  # 
    with(as.list(c(state, parms)),{
        
        # Change in SUSCEPTIBLE
        dS <- - rho[i] * beta * S * I 
        
        # Change in EXPOSED
        dE <- rho[i] * beta * S * I - alpha * E
        
        # Change in INFECTED
        dI <- alpha * E - gamma * I
        
        # Change in RECOVERED
        dR <- gamma * I 
        
    return(list(c(dS, dE, dI, dR, rho)))
    })
}
# Set parameteres and intial conditions   ***THESE CONDITIONS ARE VERY SENSITIVE AND UNKNOWN IN REALITY***
time <- seq(1, 180, by = 1)
rho_start = 0.6
rho_end = 1
rho_diff = abs(rho_end - rho_start)
rho = seq(rho_start, rho_end, by = rho_diff/length(time))
init <- c(S =1-.001, E =.001, I = 0, R = 0, rho) # assuming 0.1% of the population has been infected
parms <- c(alpha = 0.2, beta = 2, gamma = 1) # assuming a stay at home order that reduces social contact by 20%
# NOTE: Let us define R0 = betta/gamma, which is how fast the disease spreads
# When R0 > 1 the disease will grow exponentially, likewise R0 < 1 dies exponentially

# Solve using ODE
out <- ode(y = init, times = time, func = SEIR, parms = parms)

# Change to data frame
out <- as.data.frame(out)
out$time <- time # Delete time variable
# 
# ggplot(data=out, aes(x = time)) +
#   geom_point(aes(y=rho, color="Rho"))


out_clean<- out %>% 
  select(time, S, E, I, R, V6)


#Plot results
ggplot(data=out_clean, aes(x = time)) +
  geom_point(aes(y=S, color="Susceptible")) +
  geom_point(aes(y=E, color="Exposed")) +
  geom_point(aes(y=I, color="Infected")) +
  geom_point(aes(y=R, color="Recovered (Immune)")) +
  # scale_colour_manual(name=) +
  theme_minimal() +
  labs(x = "Days", y = "Percent of Population", color = "")
```

Make data data set that accounts for 
```{r}

mean_temp<- rnorm(n = 180, mean = 65, sd = 5) # normal distribution of temperature
avg_mile_day = 974219178 # averge miles driven a day in CA noramlly
weather_coeff = 1000000 # coefficient of weather on averge miles driven a day in CA
shelter_coeff = 1000000 # coefficient of shelter strength on miles driven a day in CA
mile_emissions = 0.411 # Emissions factor of 1 mile driven 
# add mean temperature into the covid data 
out_clean$temp<- mean_temp
# Put in a for loop for miles driven as dependant on infections_shelter and temperature

out_clean$miles_driven<- rep(NA, 180)

for (i in length(out_clean$time)){
  out_clean$miles_driven = avg_mile_day + weather_coeff * (out_clean$temp - mean(out_clean$temp)) + shelter_coeff * (out_clean$V6)
}
# loop for ghg emissions
for (i in length(out_clean$time)){
  out_clean$ghg = out_clean$miles_driven * mile_emissions
}
```

Vizuals for GHG emissiona and driving
```{r}
options(scipen = 99)

# plot for driving
drive<- ggplot(out_clean, aes(x = time, y = ghg))+
  geom_line(color = "darkorange4")+
  theme_minimal()+
  labs(x = "Time", y = "kgCO2e", title = "Mobile GHG Emission", subtitle = "Impact of weather and shelter in place measures")
drive
```

Sobol sensativity on gamma and beta
```{r}
ghg = function(avg_mile_day, weather_coeff, shelter_coeff, mean_temp, V6){
  miles_driven = avg_mile_day + weather_coeff * temp - mean(temp) + shelter_coeff * V6
  ghg = miles_driven * mile_emissions
  
  return(list(ghg))
}


# establish the number of runs
np = 1000

# make one distribution 
weather_coeff<- rnorm(mean = 1000000, sd = 500, n = np)
shelter_coeff<- rnorm(mean = 1000000, sd = 500, n = np)

# make a data frame of this gamma
X1<- cbind.data.frame(weather_coeff, shelter_coeff)

# make a second data set
weather_coeff<- rnorm(mean = 1000000, sd = 500, n = np)
shelter_coeff<- rnorm(mean = 1000000, sd = 500, n = np)

# make a data frame of this gamma
X2<- cbind.data.frame(weather_coeff, shelter_coeff)

# apply sobol
covid_sens<- sobol2007(model = NULL, X1, X2, nboot = 100)

# avg_mile_day = 974219178
mean_temp<- rnorm(n = 180, mean = 65, sd = 5) 



# Run model for all parameter sets
res = mapply(FUN = ghg,
             weather_coeff = covid_sens$X$weather_coeff,
             shelter_coeff = covid_sens$X$shelter_coeff,
             MoreArgs = list(avg_mile_day = 974219178,
                             mean_temp = mean_temp,
                             V6 = out_clean$V6
                             ))
res<- unlist(res)

ghg_sobel = sensitivity::tell(covid_sens, res, res.names = "ga")

# first-order indices 
ghg_sobel$S

# total sensitivity index 
ghg_sobel$T

print(ghg_sobel)
plot(ghg_sobel)


# make a data frame for plotting
both = cbind.data.frame(ghg_sobel$X, gs=ghg_sobel$y)

```




